#!/bin/bash

# Color magic
BOLD="$(tput bold)"
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
RESET="$(tput sgr0)"

# Check arguments before doing anything stupid
if [ $# -ne 1 ]
then
                echo -n "$RED$BOLD"
                echo "Usage: $0 conservative|ondemand|userspace|powersave|performance$RESET"
                exit 1
fi

NEW=""
case "$1" in
	conservative)
		NEW="$1"
	;;
	ondemand)
		NEW="$1"
	;;
	userspace)
		NEW="$1"
	;;
	powersave)
		NEW="$1"
	;;
	performance)
		NEW="$1"
	;;
	*)
		echo -n "$RED$BOLD"
		echo "Usage: $0 conservative|ondemand|userspace|powersave|performance$RESET"
		exit 1
	;;
esac

# Check we are root
if [ "$(whoami)" == "root" ]
then
	echo "Setting scaling governor to$BOLD$RED performance$RESET for all cpu cores"
	
	# Replace governor for each cpu core
	echo "$NEW" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo "$NEW" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
	echo "$NEW" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
	echo "$NEW" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor

	echo -n "$BOLD$GREEN"
	echo "Done $RESET"
	exit 0
else
	# You shall not pass!
	echo -n "$BOLD$RED"
	echo "Script must be run as root, try sudo $0 $RESET"
	exit 2
fi